export const MODAL_ANIMATION_DURATION = 700;
export const MODAL_NEAR_CLOSE_DELAY = MODAL_ANIMATION_DURATION * 0.8;
export const SPOILER_ANIMATION_MIN_DURATION = 450;
export const SPOILER_ANIMATION_MAX_DURATION = 1350;
export const ACHIEVEMENT_CLICK_DELAY = 300;
export const SCROLLBAR_WIDTH_PROPERTY_NAME = '--scrollbar-width';